name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy project files to Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_SSH_PASSWORD }}
          source: "."
          target: "~/Hexplain"

      - name: Build and Restart Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_SSH_PASSWORD }}
          script: |
            cd ~/Hexplain
            
            # Restart all containers with the new code
            docker compose down
            docker compose up -d --build
            
            # Prune dangling images
            docker image prune -f
